[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "14.15.0"
  NPM_VERSION = "6.14.8"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/typeit"
  to = "https://typeitjs.com"
  status = 301

[[redirects]]
  from = "/posts/page/1"
  to = "/posts"
  status = 301

[[redirects]]
  from = "/posts/lazy-load-images-in-wordpress-without-a-plugin"
  to = "/posts/build-your-own-simple-lazy-loading-functionality-in-wordpress"
  status = 301

[[redirects]]
  from = "/bell"
  to = "https://alexmacarthur.github.io/bell"
  status = 301

[[redirects]]
  from = "/notes/*"
  to = "/posts/:splat"
  status = 301

[[redirects]]
  from = "/posts/cleaning-up-redux-store-listeners-when-component-state-updates"
  to = "/posts/clean-up-your-redux-store-listeners-when-component-state-updates"
  status = 301

[[redirects]]
  from = "/posts/blog-for-your-own-sake"
  to = "https://www.ramseyinhouse.com/blog/as-an-engineer-write"
  status = 301

